language: python
python:
- 2.7
- 3.3
- 3.4
install:
- sudo apt-get install -y xvfb
- export WHEELHOUSE=$PWD/wheelhouse
- bash buildpyside.sh
- bash buildpyside2.sh
script:
- Xvfb :0 -screen 0 1600x1200x24 &
- export DISPLAY=:0.0
- bash test.sh
- bash test2.sh
after_success:
- bash deploy.sh
env:
  global:
  - GITHUBUSERNAME=storax
  - secure: c6ROZEYB7/GTuSyyCA5IptXfbz66GQo+/UiDvWZWNQIqT5g3SERLJOd3cObWQgRnEW6xaomZ3Vlqci83ZlK08a2kv387HdLBo+A+6GG/X19JCgRo7g6zajW0VaHXv+7Q2GhTdOvaaXID69jHNhOfjDKK/knKaOH5OTNmK3uZBYM=
