# Build pyside wheels for the travis worker
language: python
python:
    - 2.7
    - 3.3
    - 3.4
install:
    - export WHEELHOUSE=$PWD/wheelhouse
    - bash buildpyside.sh
script:
    - pip install -v -f $WHEELHOUSE --no-index pyside
    # Post install needed for pyside wheel
    - python $WHEELHOUSE/pyside_postinstall.py -install
    # Smoke test
    - python -c "from PySide.QtGui import *"
    - python sampleapp.py